from AutoTrader.ml.data_collector.features_generator.auto_features_generator import AutoFeaturesGenerator
from AutoTrader.ml.data_collector.features_generator.simple_features_generator import SimpleFeaturesGenerator
